# Select the Agent to run the builds on
pool:
  vmImage: 'macOS 10.13'

steps:
# To manually select a Xamarin SDK version on the Microsoft-hosted macOS agent,
# configure this task with the SDK version you want to target and set the "enabled" property to true.
# See https://go.microsoft.com/fwlink/?linkid=871629
- script: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 5_4_1 
  displayName: 'Select the Xamarin SDK version'
  enabled: false

# Install NuGet on Build Agend and restore packages
- task: NuGetToolInstaller@0
- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

# Build iOS Application
- task: XamariniOS@2
  inputs:
    solutionFile: '**/*.iOS.csproj'
    configuration: '$(BuildConfiguration)'
    buildForSimulator: true
    packageApp: false

# Build Android Application
- task: XamarinAndroid@1
  inputs:
    projectFile: '**/*.Droid.csproj'
    configuration: '$(BuildConfiguration)'
    msbuildVersionOption: latest
    
# Build UI Tests
- task: MSBuild@1
  inputs:
    solution: '**/*.UITests.csproj'
    configuration: '$(BuildConfiguration)'

